<div style="display: flex; justify-content: center;">
    <img src="./IA/robo1.jpg" style="border-radius: 20px; width: 75%;">
</div>

<small> Imagen creada por IA generativa usando el siguiente pront: 'Estoy haciendo un Jupyter Notebook en el que preparo datos para ser usados. La cabecera quiero que me quede bonita. ¿Podrías generarme una imagen de un robot cocinando datos, no muy complejo, con un fondo simple? (Luego editada con paint)'<small>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import os

### En este Jupyter Notebook preparé los archivos con los datos que recogen la información de los vehículos retirados de la vía pública de Madrid, desde 2016 hasta 2023.

Los archivos, en formato CSV y uno para cada año, tienen las siguientes columnas:

- **idVehiculo**: Es un identificador alfanumérico para cada vehículo.
- **deposito**: El nombre del depósito al que se llevó el vehículo en cuestión.
- **tipoVehiculo**: Es un código numérico que indica el tipo de vehículo en cuestión. El significado del código está indicado en un archivo CSV auxiliar.
- **motivo**: Es un código numérico que indica el motivo por el que se retiró el vehículo de la vía pública. El significado del código está indicado en un archivo CSV auxiliar.
- **Turno**: Es un código numérico que indica el turno en el que se retiró el vehículo. El significado del código está indicado en un archivo CSV auxiliar.
- **Grua**: Es un código alfanumérico que indica la grúa que retiró el vehículo.
- **fechaEntrada**: Indica la fecha y hora en que se retiró el vehículo de la vía publica.
- **tipoVia**: Indica el tipo de vía desde la cual se retiró el vehículo.
- **Via**: Nombre de la vía.
- **numero**: Número de la vía.
- **cp**: Código postal de la vía.

In [2]:
años = ['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']
for año in años:
    print(f'entradas{año} = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/{año}Entradas.csv", encoding="UTF-8", sep=";")')

entradas2016 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2016Entradas.csv", encoding="UTF-8", sep=";")
entradas2017 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2017Entradas.csv", encoding="UTF-8", sep=";")
entradas2018 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2018Entradas.csv", encoding="UTF-8", sep=";")
entradas2019 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2019Entradas.csv", encoding="UTF-8", sep=";")
entradas2020 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2020Entradas.csv", encoding="UTF-8", sep=";")
entradas2021 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2021Entradas.csv", encoding="UTF-8", sep=";")
entradas2022 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2022Entradas.csv", encoding="UTF-8", sep=";")
entradas2023 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2023Entradas.csv", encoding="UTF-8", sep=";")

> Con este código me ahorro el trabajo de escribir uno a uno la línea necesaria para leer cada archivo CSV.

In [3]:
entradas2016 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2016Entradas.csv", encoding="UTF-8", sep=";")
entradas2017 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2017Entradas.csv", encoding="UTF-8", sep=";")
entradas2018 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2018Entradas.csv", encoding="UTF-8", sep=";")
entradas2019 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2019Entradas.csv", encoding="UTF-8", sep=";")
entradas2020 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2020Entradas.csv", encoding="UTF-8", sep=";")
entradas2021 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2021Entradas.csv", encoding="UTF-8", sep=";")
entradas2022 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2022Entradas.csv", encoding="UTF-8", sep=";")
entradas2023 = pd.read_csv("C:/Users/pepea/Desktop/the_drige/EDA/Dataset/datos/entradas/2023Entradas.csv", encoding="UTF-8", sep=";")

>Hago copia/pega

>>Después de visualizar el DataFrame de cada año, noté que en el año 2016 había una columna llamada 'Unnamed: 11' con solo una entrada válida, la cual no existe en ningún otro año. Por lo tanto, procedo a eliminarla.

In [4]:
entradas2016 = entradas2016.drop('Unnamed: 11', axis=1)

La columna 'fechaEntrada' no tiene el mismo formato en todos los años. Además, incluye la hora y no está en formato datetime.  
Haré que todos los años tengan el mismo formato, separaré la fecha y la hora, y luego lo convertiré al formato de fecha antes de unir los DataFrames.

In [5]:
fecha_primeros_años = ['2016', '2017', '2018', '2019', '2020']
for año_s in fecha_primeros_años:
    print(f'#Codigo para en año {año_s}')
    print(f"entradas{año_s}['Fecha_Entrada'] = pd.to_datetime(entradas{año_s}['fechaEntrada'], format='%d/%m/%Y %H:%M')")
    print(f"entradas{año_s}['Fecha_e'] = entradas{año_s}['Fecha_Entrada'].dt.date")
    print(f"entradas{año_s}['Fecha_e'] =  pd.to_datetime(entradas{año_s}['Fecha_e'])")
    print(f"entradas{año_s}['Hora_e'] = entradas{año_s}['Fecha_Entrada'].dt.time")
    print(f"entradas{año_s} = entradas{año_s}.drop('fechaEntrada', axis=1)")
    print(f"entradas{año_s} = entradas{año_s}.drop('Fecha_Entrada', axis=1)")
    print(f"entradas{año_s}= entradas{año_s}[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]")
    print()

#Codigo para en año 2016
entradas2016['Fecha_Entrada'] = pd.to_datetime(entradas2016['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2016['Fecha_e'] = entradas2016['Fecha_Entrada'].dt.date
entradas2016['Fecha_e'] =  pd.to_datetime(entradas2016['Fecha_e'])
entradas2016['Hora_e'] = entradas2016['Fecha_Entrada'].dt.time
entradas2016 = entradas2016.drop('fechaEntrada', axis=1)
entradas2016 = entradas2016.drop('Fecha_Entrada', axis=1)
entradas2016= entradas2016[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2017
entradas2017['Fecha_Entrada'] = pd.to_datetime(entradas2017['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2017['Fecha_e'] = entradas2017['Fecha_Entrada'].dt.date
entradas2017['Fecha_e'] =  pd.to_datetime(entradas2017['Fecha_e'])
entradas2017['Hora_e'] = entradas2017['Fecha_Entrada'].dt.time
entradas2017 = entradas2017.drop('fechaEntrada', axis=1)
entradas2017 = entradas2017.drop('Fecha_Entrada', axis=1)
entradas2017= entradas2017[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2018
entradas2018['Fecha_Entrada'] = pd.to_datetime(entradas2018['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2018['Fecha_e'] = entradas2018['Fecha_Entrada'].dt.date
entradas2018['Fecha_e'] =  pd.to_datetime(entradas2018['Fecha_e'])
entradas2018['Hora_e'] = entradas2018['Fecha_Entrada'].dt.time
entradas2018 = entradas2018.drop('fechaEntrada', axis=1)
entradas2018 = entradas2018.drop('Fecha_Entrada', axis=1)
entradas2018= entradas2018[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2019
entradas2019['Fecha_Entrada'] = pd.to_datetime(entradas2019['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2019['Fecha_e'] = entradas2019['Fecha_Entrada'].dt.date
entradas2019['Fecha_e'] =  pd.to_datetime(entradas2019['Fecha_e'])
entradas2019['Hora_e'] = entradas2019['Fecha_Entrada'].dt.time
entradas2019 = entradas2019.drop('fechaEntrada', axis=1)
entradas2019 = entradas2019.drop('Fecha_Entrada', axis=1)
entradas2019= entradas2019[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2020
entradas2020['Fecha_Entrada'] = pd.to_datetime(entradas2020['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2020['Fecha_e'] = entradas2020['Fecha_Entrada'].dt.date
entradas2020['Fecha_e'] =  pd.to_datetime(entradas2020['Fecha_e'])
entradas2020['Hora_e'] = entradas2020['Fecha_Entrada'].dt.time
entradas2020 = entradas2020.drop('fechaEntrada', axis=1)
entradas2020 = entradas2020.drop('Fecha_Entrada', axis=1)
entradas2020= entradas2020[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

In [6]:
#Codigo para en año 2016
entradas2016['Fecha_Entrada'] = pd.to_datetime(entradas2016['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2016['Fecha_e'] = entradas2016['Fecha_Entrada'].dt.date
entradas2016['Fecha_e'] =  pd.to_datetime(entradas2016['Fecha_e'])
entradas2016['Hora_e'] = entradas2016['Fecha_Entrada'].dt.time
entradas2016 = entradas2016.drop('fechaEntrada', axis=1)
entradas2016 = entradas2016.drop('Fecha_Entrada', axis=1)
entradas2016= entradas2016[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2017
entradas2017['Fecha_Entrada'] = pd.to_datetime(entradas2017['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2017['Fecha_e'] = entradas2017['Fecha_Entrada'].dt.date
entradas2017['Fecha_e'] =  pd.to_datetime(entradas2017['Fecha_e'])
entradas2017['Hora_e'] = entradas2017['Fecha_Entrada'].dt.time
entradas2017 = entradas2017.drop('fechaEntrada', axis=1)
entradas2017 = entradas2017.drop('Fecha_Entrada', axis=1)
entradas2017= entradas2017[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2018
entradas2018['Fecha_Entrada'] = pd.to_datetime(entradas2018['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2018['Fecha_e'] = entradas2018['Fecha_Entrada'].dt.date
entradas2018['Fecha_e'] =  pd.to_datetime(entradas2018['Fecha_e'])
entradas2018['Hora_e'] = entradas2018['Fecha_Entrada'].dt.time
entradas2018 = entradas2018.drop('fechaEntrada', axis=1)
entradas2018 = entradas2018.drop('Fecha_Entrada', axis=1)
entradas2018= entradas2018[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2019
entradas2019['Fecha_Entrada'] = pd.to_datetime(entradas2019['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2019['Fecha_e'] = entradas2019['Fecha_Entrada'].dt.date
entradas2019['Fecha_e'] =  pd.to_datetime(entradas2019['Fecha_e'])
entradas2019['Hora_e'] = entradas2019['Fecha_Entrada'].dt.time
entradas2019 = entradas2019.drop('fechaEntrada', axis=1)
entradas2019 = entradas2019.drop('Fecha_Entrada', axis=1)
entradas2019= entradas2019[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2020
entradas2020['Fecha_Entrada'] = pd.to_datetime(entradas2020['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2020['Fecha_e'] = entradas2020['Fecha_Entrada'].dt.date
entradas2020['Fecha_e'] =  pd.to_datetime(entradas2020['Fecha_e'])
entradas2020['Hora_e'] = entradas2020['Fecha_Entrada'].dt.time
entradas2020 = entradas2020.drop('fechaEntrada', axis=1)
entradas2020 = entradas2020.drop('Fecha_Entrada', axis=1)
entradas2020= entradas2020[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

In [7]:
fecha_ultimos_años = ['2021', '2022', '2023']
for año_s in fecha_ultimos_años:
    print(f'#Codigo para en año {año_s}')
    print(f"entradas{año_s}['Fecha_Entrada'] = pd.to_datetime(entradas{año_s}['fechaEntrada'], format='%d/%m/%Y %H:%M')")
    print(f"entradas{año_s}['Fecha_e'] = entradas{año_s}['Fecha_Entrada'].dt.date")
    print(f"entradas{año_s}['Fecha_e'] =  pd.to_datetime(entradas{año_s}['Fecha_e'])")
    print(f"entradas{año_s}['Hora_e'] = entradas{año_s}['Fecha_Entrada'].dt.time")
    print(f"entradas{año_s} = entradas{año_s}.drop('fechaEntrada', axis=1)")
    print(f"entradas{año_s} = entradas{año_s}.drop('Fecha_Entrada', axis=1)")
    print(f"entradas{año_s}= entradas{año_s}[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]")
    print()

#Codigo para en año 2021
entradas2021['Fecha_Entrada'] = pd.to_datetime(entradas2021['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2021['Fecha_e'] = entradas2021['Fecha_Entrada'].dt.date
entradas2021['Fecha_e'] =  pd.to_datetime(entradas2021['Fecha_e'])
entradas2021['Hora_e'] = entradas2021['Fecha_Entrada'].dt.time
entradas2021 = entradas2021.drop('fechaEntrada', axis=1)
entradas2021 = entradas2021.drop('Fecha_Entrada', axis=1)
entradas2021= entradas2021[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2022
entradas2022['Fecha_Entrada'] = pd.to_datetime(entradas2022['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2022['Fecha_e'] = entradas2022['Fecha_Entrada'].dt.date
entradas2022['Fecha_e'] =  pd.to_datetime(entradas2022['Fecha_e'])
entradas2022['Hora_e'] = entradas2022['Fecha_Entrada'].dt.time
entradas2022 = entradas2022.drop('fechaEntrada', axis=1)
entradas2022 = entradas2022.drop('Fecha_Entrada', axis=1)
entradas2022= entradas2022[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2023
entradas2023['Fecha_Entrada'] = pd.to_datetime(entradas2023['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2023['Fecha_e'] = entradas2023['Fecha_Entrada'].dt.date
entradas2023['Fecha_e'] =  pd.to_datetime(entradas2023['Fecha_e'])
entradas2023['Hora_e'] = entradas2023['Fecha_Entrada'].dt.time
entradas2023 = entradas2023.drop('fechaEntrada', axis=1)
entradas2023 = entradas2023.drop('Fecha_Entrada', axis=1)
entradas2023= entradas2023[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

In [8]:
#Codigo para en año 2021
entradas2021['Fecha_Entrada'] = pd.to_datetime(entradas2021['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2021['Fecha_e'] = entradas2021['Fecha_Entrada'].dt.date
entradas2021['Fecha_e'] =  pd.to_datetime(entradas2021['Fecha_e'])
entradas2021['Hora_e'] = entradas2021['Fecha_Entrada'].dt.time
entradas2021 = entradas2021.drop('fechaEntrada', axis=1)
entradas2021 = entradas2021.drop('Fecha_Entrada', axis=1)
entradas2021= entradas2021[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2022
entradas2022['Fecha_Entrada'] = pd.to_datetime(entradas2022['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2022['Fecha_e'] = entradas2022['Fecha_Entrada'].dt.date
entradas2022['Fecha_e'] =  pd.to_datetime(entradas2022['Fecha_e'])
entradas2022['Hora_e'] = entradas2022['Fecha_Entrada'].dt.time
entradas2022 = entradas2022.drop('fechaEntrada', axis=1)
entradas2022 = entradas2022.drop('Fecha_Entrada', axis=1)
entradas2022= entradas2022[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

#Codigo para en año 2023
entradas2023['Fecha_Entrada'] = pd.to_datetime(entradas2023['fechaEntrada'], format='%d/%m/%Y %H:%M')
entradas2023['Fecha_e'] = entradas2023['Fecha_Entrada'].dt.date
entradas2023['Fecha_e'] =  pd.to_datetime(entradas2023['Fecha_e'])
entradas2023['Hora_e'] = entradas2023['Fecha_Entrada'].dt.time
entradas2023 = entradas2023.drop('fechaEntrada', axis=1)
entradas2023 = entradas2023.drop('Fecha_Entrada', axis=1)
entradas2023= entradas2023[['idVehiculo', 'deposito', 'tipoVehiculo', 'motivo', 'turno','Fecha_e', 'Hora_e', 'grua', 'tipoVia', 'via', 'numero', 'cp']]

La fecha tiene el mismo formato y hay una columna con la hora. Ahora es necesario añadir la información de turno y tipo de vehículo,  
además de una columna de booleanos para saber si es o no fin de semana.

>La información está en las tablas auxiliares.

>>Para conocer el significado de los códigos "6.0", "7.0" y "8.0", que no aparecían en la tabla auxiliar "Tipos_Vehiculo.csv",  
envié un correo electrónico al organismo pertinente.

In [9]:
todos_los_años = ['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']
tipo_de_vehiculo = { 1: "Motocicleta",2: "Motocarro",3: "Coche",4: "Camión",5: "Vehículo pesado", 6.0: "Bicicletas",7.0: "Patinetes (VMP)",8.0: "Remolque",} #procede de CSV auxuliares
tipo_turno = {1:"Mañana", 2:"Tarde", 3:"Noche"}
for año_info in todos_los_años:
    print(f'#Codigo para en año {año_info}')
    print(f"entradas{año_info}['turno'] = entradas{año_info}['turno'].replace(tipo_turno)")
    print(f"entradas{año_info}['tipoVehiculo'] = entradas{año_info}['tipoVehiculo'].replace(tipo_de_vehiculo)")
    print(f"entradas{año_info}['FinDeSema'] = entradas{año_info}['Fecha_e'].dt.dayofweek >= 5")
    print(f'entradas{año_info}= entradas{año_info}[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]')
    print()

#Codigo para en año 2016
entradas2016['turno'] = entradas2016['turno'].replace(tipo_turno)
entradas2016['tipoVehiculo'] = entradas2016['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2016['FinDeSema'] = entradas2016['Fecha_e'].dt.dayofweek >= 5
entradas2016= entradas2016[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2017
entradas2017['turno'] = entradas2017['turno'].replace(tipo_turno)
entradas2017['tipoVehiculo'] = entradas2017['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2017['FinDeSema'] = entradas2017['Fecha_e'].dt.dayofweek >= 5
entradas2017= entradas2017[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2018
entradas2018['turno'] = entradas2018['turno'].replace(tipo_turno)
entradas2018['tipoVehiculo'] = entradas2018['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2018['FinDeSema'] = entradas2018['Fecha_e'].dt.dayofweek >= 5
entradas2018= entradas2018[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2019
entradas2019['turno'] = entradas2019['turno'].replace(tipo_turno)
entradas2019['tipoVehiculo'] = entradas2019['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2019['FinDeSema'] = entradas2019['Fecha_e'].dt.dayofweek >= 5
entradas2019= entradas2019[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2020
entradas2020['turno'] = entradas2020['turno'].replace(tipo_turno)
entradas2020['tipoVehiculo'] = entradas2020['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2020['FinDeSema'] = entradas2020['Fecha_e'].dt.dayofweek >= 5
entradas2020= entradas2020[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2021
entradas2021['turno'] = entradas2021['turno'].replace(tipo_turno)
entradas2021['tipoVehiculo'] = entradas2021['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2021['FinDeSema'] = entradas2021['Fecha_e'].dt.dayofweek >= 5
entradas2021= entradas2021[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2022
entradas2022['turno'] = entradas2022['turno'].replace(tipo_turno)
entradas2022['tipoVehiculo'] = entradas2022['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2022['FinDeSema'] = entradas2022['Fecha_e'].dt.dayofweek >= 5
entradas2022= entradas2022[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2023
entradas2023['turno'] = entradas2023['turno'].replace(tipo_turno)
entradas2023['tipoVehiculo'] = entradas2023['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2023['FinDeSema'] = entradas2023['Fecha_e'].dt.dayofweek >= 5
entradas2023= entradas2023[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

In [10]:
#Codigo para en año 2016
entradas2016['turno'] = entradas2016['turno'].replace(tipo_turno)
entradas2016['tipoVehiculo'] = entradas2016['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2016['FinDeSema'] = entradas2016['Fecha_e'].dt.dayofweek >= 5
entradas2016= entradas2016[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2017
entradas2017['turno'] = entradas2017['turno'].replace(tipo_turno)
entradas2017['tipoVehiculo'] = entradas2017['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2017['FinDeSema'] = entradas2017['Fecha_e'].dt.dayofweek >= 5
entradas2017= entradas2017[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2018
entradas2018['turno'] = entradas2018['turno'].replace(tipo_turno)
entradas2018['tipoVehiculo'] = entradas2018['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2018['FinDeSema'] = entradas2018['Fecha_e'].dt.dayofweek >= 5
entradas2018= entradas2018[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2019
entradas2019['turno'] = entradas2019['turno'].replace(tipo_turno)
entradas2019['tipoVehiculo'] = entradas2019['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2019['FinDeSema'] = entradas2019['Fecha_e'].dt.dayofweek >= 5
entradas2019= entradas2019[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2020
entradas2020['turno'] = entradas2020['turno'].replace(tipo_turno)
entradas2020['tipoVehiculo'] = entradas2020['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2020['FinDeSema'] = entradas2020['Fecha_e'].dt.dayofweek >= 5
entradas2020= entradas2020[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2021
entradas2021['turno'] = entradas2021['turno'].replace(tipo_turno)
entradas2021['tipoVehiculo'] = entradas2021['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2021['FinDeSema'] = entradas2021['Fecha_e'].dt.dayofweek >= 5
entradas2021= entradas2021[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2022
entradas2022['turno'] = entradas2022['turno'].replace(tipo_turno)
entradas2022['tipoVehiculo'] = entradas2022['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2022['FinDeSema'] = entradas2022['Fecha_e'].dt.dayofweek >= 5
entradas2022= entradas2022[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

#Codigo para en año 2023
entradas2023['turno'] = entradas2023['turno'].replace(tipo_turno)
entradas2023['tipoVehiculo'] = entradas2023['tipoVehiculo'].replace(tipo_de_vehiculo)
entradas2023['FinDeSema'] = entradas2023['Fecha_e'].dt.dayofweek >= 5
entradas2023= entradas2023[["idVehiculo","deposito","tipoVehiculo",	"motivo","turno","Fecha_e","FinDeSema","Hora_e","grua","tipoVia","via","numero","cp"]]

Dado que quería comprobar si el ser o no festivo afectaba a la retirada de vehículos,  
añadí una columna con el nombre de cada festividad o "No festivo" en caso de no serlo.

>La información la saqué de la página del ayuntamiento.

In [11]:
festivos = {"2016-01-01": "Año Nuevo","2016-01-06": "Día de Reyes","2016-04-13": "Jueves Santo","2016-04-14": "Viernes Santo","2016-05-01": "Día del Trabajador","2016-05-02": "Día de la Comunidad de Madrid",
    "2016-08-15": "Asunción de la Virgen","2016-10-12": "Fiesta Nacional de España","2016-11-01": "Día de Todos los Santos","2016-12-06": "Día de la Constitución","2016-12-08": "Inmaculada Concepción","2016-12-25": "Navidad","2016-05-15": "San Isidro",
    "2017-01-01": "Año Nuevo","2017-01-06": "Día de Reyes","2017-04-13": "Jueves Santo","2017-04-13": "Viernes Santo","2017-05-01": "Día del Trabajador","2017-05-02": "Día de la Comunidad de Madrid","2017-08-15": "Asunción de la Virgen", "2017-10-12": "Fiesta Nacional de España",
    "2017-11-01": "Día de Todos los Santos","2017-12-06": "Día de la Constitución","2017-12-08": "Inmaculada Concepción","2017-12-25": "Navidad","2017-05-15": "San Isidro",
    "2018-01-01": "Año Nuevo","2018-01-06": "Día de Reyes","2018-03-29": "Jueves Santo","2018-03-30": "Viernes Santo","2018-05-01": "Día del Trabajador","2018-05-02": "Día de la Comunidad de Madrid","2018-08-15": "Asunción de la Virgen",
    "2018-10-12": "Fiesta Nacional de España","2018-11-01": "Día de Todos los Santos","2018-12-06": "Día de la Constitución","2018-12-08": "Inmaculada Concepción","2018-12-25": "Navidad","2018-05-15": "San Isidro", 
    "2019-01-01": "Año Nuevo","2019-01-06": "Día de Reyes","2019-04-18": "Jueves Santo","2019-04-19": "Viernes Santo","2019-05-01": "Día del Trabajador",
    "2019-05-02": "Día de la Comunidad de Madrid","2019-08-15": "Asunción de la Virgen","2019-10-12": "Fiesta Nacional de España","2019-11-01": "Día de Todos los Santos","2019-12-06": "Día de la Constitución","2019-12-08": "Inmaculada Concepción","2019-12-25": "Navidad","2019-05-15": "San Isidro",
    "2020-01-01": "Año Nuevo","2020-01-06": "Día de Reyes","2020-04-09": "Jueves Santo","2020-04-10": "Viernes Santo","2020-05-01": "Día del Trabajador","2020-05-02": "Día de la Comunidad de Madrid","2020-08-15": "Asunción de la Virgen","2020-10-12": "Fiesta Nacional de España","2020-11-01": "Día de Todos los Santos","2020-12-06": "Día de la Constitución","2020-12-08": "Inmaculada Concepción","2020-12-25": "Navidad","2020-05-15": "San Isidro","2021-01-01": "Año Nuevo","2021-01-06": "Día de Reyes","2021-04-01": "Jueves Santo","2021-04-02": "Viernes Santo","2021-05-01": "Día del Trabajador","2021-05-02": "Día de la Comunidad de Madrid","2021-08-15": "Asunción de la Virgen","2021-10-12": "Fiesta Nacional de España","2021-11-01": "Día de Todos los Santos","2021-12-06": "Día de la Constitución","2021-12-08": "Inmaculada Concepción","2021-12-25": "Navidad","2021-05-15": "San Isidro",
    "2022-01-01": "Año Nuevo","2022-01-06": "Día de Reyes","2022-04-07": "Jueves Santo","2022-04-08": "Viernes Santo","2022-05-01": "Día del Trabajador","2022-05-02": "Día de la Comunidad de Madrid","2022-08-15": "Asunción de la Virgen","2022-10-12": "Fiesta Nacional de España","2022-11-01": "Día de Todos los Santos","2022-12-06": "Día de la Constitución","2022-12-08": "Inmaculada Concepción","2022-12-25": "Navidad","2022-05-15": "San Isidro","2023-01-01": "Año Nuevo","2023-01-06": "Día de Reyes","2023-04-13": "Jueves Santo","2023-04-14": "Viernes Santo","2023-05-01": "Día del Trabajador","2023-05-02": "Día de la Comunidad de Madrid","2023-08-15": "Asunción de la Virgen","2023-10-12": "Fiesta Nacional de España","2023-11-01": "Día de Todos los Santos","2023-12-06": "Día de la Constitución","2023-12-08": "Inmaculada Concepción","2023-12-25": "Navidad","2023-05-15": "San Isidro",
    }

In [12]:
todos_los_años = ['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023'] 

for año_ob in todos_los_años:
    print(f'#Para el año {año_ob}')
    print(f'entradas{año_ob}["fecha objeto"] = entradas{año_ob}["Fecha_e"].astype("object")') #para añadir la festividad necesitamos que sea tipo objeto, para poder usar split
    print(f"entradas{año_ob}['fecha objeto'] = entradas{año_ob}['Fecha_e'].astype(str).str.split().str[0]")
    print(f"entradas{año_ob}['Festivo'] = entradas{año_ob}['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))") #si la clave (fecha) está en festivos, pon el valor (el nombre de la festividad), si no está... pon "no festivo", obvimante.
    print(f"entradas{año_ob} = entradas{año_ob}.drop('fecha objeto', axis=1)")
    print(f"entradas{año_ob}= entradas{año_ob}[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]") #Con esto ordeno la tabla.
    print()

#Para el año 2016
entradas2016["fecha objeto"] = entradas2016["Fecha_e"].astype("object")
entradas2016['fecha objeto'] = entradas2016['Fecha_e'].astype(str).str.split().str[0]
entradas2016['Festivo'] = entradas2016['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2016 = entradas2016.drop('fecha objeto', axis=1)
entradas2016= entradas2016[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2017
entradas2017["fecha objeto"] = entradas2017["Fecha_e"].astype("object")
entradas2017['fecha objeto'] = entradas2017['Fecha_e'].astype(str).str.split().str[0]
entradas2017['Festivo'] = entradas2017['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2017 = entradas2017.drop('fecha objeto', axis=1)
entradas2017= entradas2017[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2018
entradas2018["fecha objeto"] = entradas2018["Fecha_e"].astype("object")
entradas2018['fecha objeto'] = entradas2018['Fecha_e'].astype(str).str.split().str[0]
entradas2018['Festivo'] = entradas2018['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2018 = entradas2018.drop('fecha objeto', axis=1)
entradas2018= entradas2018[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2019
entradas2019["fecha objeto"] = entradas2019["Fecha_e"].astype("object")
entradas2019['fecha objeto'] = entradas2019['Fecha_e'].astype(str).str.split().str[0]
entradas2019['Festivo'] = entradas2019['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2019 = entradas2019.drop('fecha objeto', axis=1)
entradas2019= entradas2019[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2020
entradas2020["fecha objeto"] = entradas2020["Fecha_e"].astype("object")
entradas2020['fecha objeto'] = entradas2020['Fecha_e'].astype(str).str.split().str[0]
entradas2020['Festivo'] = entradas2020['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2020 = entradas2020.drop('fecha objeto', axis=1)
entradas2020= entradas2020[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2021
entradas2021["fecha objeto"] = entradas2021["Fecha_e"].astype("object")
entradas2021['fecha objeto'] = entradas2021['Fecha_e'].astype(str).str.split().str[0]
entradas2021['Festivo'] = entradas2021['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2021 = entradas2021.drop('fecha objeto', axis=1)
entradas2021= entradas2021[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2022
entradas2022["fecha objeto"] = entradas2022["Fecha_e"].astype("object")
entradas2022['fecha objeto'] = entradas2022['Fecha_e'].astype(str).str.split().str[0]
entradas2022['Festivo'] = entradas2022['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2022 = entradas2022.drop('fecha objeto', axis=1)
entradas2022= entradas2022[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2023
entradas2023["fecha objeto"] = entradas2023["Fecha_e"].astype("object")
entradas2023['fecha objeto'] = entradas2023['Fecha_e'].astype(str).str.split().str[0]
entradas2023['Festivo'] = entradas2023['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2023 = entradas2023.drop('fecha objeto', axis=1)
entradas2023= entradas2023[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

In [13]:
#Para el año 2016
entradas2016["fecha objeto"] = entradas2016["Fecha_e"].astype("object")
entradas2016['fecha objeto'] = entradas2016['Fecha_e'].astype(str).str.split().str[0]
entradas2016['Festivo'] = entradas2016['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2016 = entradas2016.drop('fecha objeto', axis=1)
entradas2016= entradas2016[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2017
entradas2017["fecha objeto"] = entradas2017["Fecha_e"].astype("object")
entradas2017['fecha objeto'] = entradas2017['Fecha_e'].astype(str).str.split().str[0]
entradas2017['Festivo'] = entradas2017['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2017 = entradas2017.drop('fecha objeto', axis=1)
entradas2017= entradas2017[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2018
entradas2018["fecha objeto"] = entradas2018["Fecha_e"].astype("object")
entradas2018['fecha objeto'] = entradas2018['Fecha_e'].astype(str).str.split().str[0]
entradas2018['Festivo'] = entradas2018['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2018 = entradas2018.drop('fecha objeto', axis=1)
entradas2018= entradas2018[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2019
entradas2019["fecha objeto"] = entradas2019["Fecha_e"].astype("object")
entradas2019['fecha objeto'] = entradas2019['Fecha_e'].astype(str).str.split().str[0]
entradas2019['Festivo'] = entradas2019['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2019 = entradas2019.drop('fecha objeto', axis=1)
entradas2019= entradas2019[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2020
entradas2020["fecha objeto"] = entradas2020["Fecha_e"].astype("object")
entradas2020['fecha objeto'] = entradas2020['Fecha_e'].astype(str).str.split().str[0]
entradas2020['Festivo'] = entradas2020['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2020 = entradas2020.drop('fecha objeto', axis=1)
entradas2020= entradas2020[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2021
entradas2021["fecha objeto"] = entradas2021["Fecha_e"].astype("object")
entradas2021['fecha objeto'] = entradas2021['Fecha_e'].astype(str).str.split().str[0]
entradas2021['Festivo'] = entradas2021['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2021 = entradas2021.drop('fecha objeto', axis=1)
entradas2021= entradas2021[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2022
entradas2022["fecha objeto"] = entradas2022["Fecha_e"].astype("object")
entradas2022['fecha objeto'] = entradas2022['Fecha_e'].astype(str).str.split().str[0]
entradas2022['Festivo'] = entradas2022['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2022 = entradas2022.drop('fecha objeto', axis=1)
entradas2022= entradas2022[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']]

#Para el año 2023
entradas2023["fecha objeto"] = entradas2023["Fecha_e"].astype("object")
entradas2023['fecha objeto'] = entradas2023['Fecha_e'].astype(str).str.split().str[0]
entradas2023['Festivo'] = entradas2023['fecha objeto'].apply(lambda x: festivos.get(x, 'No festivo'))
entradas2023 = entradas2023.drop('fecha objeto', axis=1)
entradas2023= entradas2023[['idVehiculo','deposito','tipoVehiculo','motivo','turno','Fecha_e',	'FinDeSema','Festivo','Hora_e','grua','tipoVia','via','numero','cp']];

In [14]:
entradas2022

,idVehiculo,deposito,tipoVehiculo,motivo,turno,Fecha_e,FinDeSema,Festivo,Hora_e,grua,tipoVia,via,numero,cp
0,CO20220101002551,COLON,Coche,6,Noche,2022-01-01,True,Año Nuevo,00:00:00,S308,CALLE,SALABERRY,42,28025
1,VC20220101011207,VICALVARO,Coche,14,Noche,2022-01-01,True,Año Nuevo,00:40:00,S318,CALLE,SAN ERASMO,0,28021
2,ES20220101015719,ESCUADRON,Coche,13,Noche,2022-01-01,True,Año Nuevo,01:50:00,S356,CALLE,MONTE PERDIDO,24,28053
3,CO20220101023413,COLON,Camión,6,Noche,2022-01-01,True,Año Nuevo,02:20:00,S348,CALLE,HURTUMPASCUAL,5,28047
4,VC20220101033959,VICALVARO,Coche,14,Noche,2022-01-01,True,Año Nuevo,03:00:00,S370,CALLE,ATOCHA,25,28012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39146,PI20221231211634,PASEO IMPERIAL,Coche,44,Tarde,2022-12-31,True,No festivo,21:15:00,S326,CALLE,JULIAN GAYARRE,12,28014
39147,RE20221231212556,EL RECUERDO,Coche,44,Tarde,2022-12-31,True,No festivo,21:24:00,S306,CALLE,NANCLARES DE OCA,26,28022
39148,VC20221231213218,VICALVARO,Motocicleta,14,Tarde,2022-12-31,True,No festivo,21:30:00,S340,CALLE,SOMBRERERIA,0,28012
39149,VC20221231213256,VICALVARO,Coche,44,Tarde,2022-12-31,True,No festivo,21:31:00,S324,CALLE,NANCLARES DE OCA,26,28022
39150,CO20221231225601,COLON,Coche,7,Noche,2022-12-31,True,No festivo,22:55:00,S346,CALLE,PRINCESA,NaN,28008

In [15]:
entradas2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38737 entries, 0 to 38736
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   idVehiculo    38737 non-null  object
 1   deposito      38737 non-null  object
 2   tipoVehiculo  38737 non-null  object
 3   motivo        38737 non-null  int64
 4   turno         38737 non-null  object
 5   Fecha_e       38737 non-null  datetime64[ns]
 6   FinDeSema     38737 non-null  bool
 7   Festivo       38737 non-null  object
 8   Hora_e        38737 non-null  object
 9   grua          38200 non-null  object
 10  tipoVia       38737 non-null  object
 11  via           38737 non-null  object
 12  numero        36507 non-null  object
 13  cp            37574 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(11)
memory usage: 3.9+ MB

Comprobar si 'idVehiculo' está repetido, el cual es un identificador y usaremos como índice, es un paso importante.

In [16]:
for año_du in todos_los_años:
    codigo = (
        f"df_actual = entradas{año_du}\n"
        f"duplicados = df_actual.duplicated(subset=['idVehiculo'])\n"
        f"total_duplicados = duplicados.sum()\n"
        f"print(f'Número total de duplicados en la columna \"idVehiculo\" el año {año_du}:', total_duplicados)\n"
        "print()"
    )
    print(codigo)

df_actual = entradas2016
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2016:', total_duplicados)
print()
df_actual = entradas2017
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2017:', total_duplicados)
print()
df_actual = entradas2018
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2018:', total_duplicados)
print()
df_actual = entradas2019
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2019:', total_duplicados)
print()
df_actual = entradas2020
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2020:', total_duplicados)
print()
df_actual = entradas2021
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2021:', total_duplicados)
print()
df_actual = entradas2022
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2022:', total_duplicados)
print()
df_actual = entradas2023
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2023:', total_duplicados)
print()

In [17]:
df_actual = entradas2016
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2016:', total_duplicados)
print()
df_actual = entradas2017
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2017:', total_duplicados)
print()
df_actual = entradas2018
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2018:', total_duplicados)
print()
df_actual = entradas2019
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2019:', total_duplicados)
print()
df_actual = entradas2020
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2020:', total_duplicados)
print()
df_actual = entradas2021
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2021:', total_duplicados)
print()
df_actual = entradas2022
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2022:', total_duplicados)
print()
df_actual = entradas2023
duplicados = df_actual.duplicated(subset=['idVehiculo'])
total_duplicados = duplicados.sum()
print(f'Número total de duplicados en la columna "idVehiculo" el año 2023:', total_duplicados)
print()

Número total de duplicados en la columna "idVehiculo" el año 2016: 0

Número total de duplicados en la columna "idVehiculo" el año 2017: 0

Número total de duplicados en la columna "idVehiculo" el año 2018: 0

Número total de duplicados en la columna "idVehiculo" el año 2019: 0

Número total de duplicados en la columna "idVehiculo" el año 2020: 0

Número total de duplicados en la columna "idVehiculo" el año 2021: 0

Número total de duplicados en la columna "idVehiculo" el año 2022: 1

Número total de duplicados en la columna "idVehiculo" el año 2023: 0

Hay solo un duplicado en el año 2022.

In [18]:
filas_duplicadas = entradas2022[entradas2022.duplicated(subset=['idVehiculo'], keep=False)]

filas_duplicadas

,idVehiculo,deposito,tipoVehiculo,motivo,turno,Fecha_e,FinDeSema,Festivo,Hora_e,grua,tipoVia,via,numero,cp
4992,CO20220219041504,COLON,Coche,42,Noche,2022-02-19,True,No festivo,04:10:00,S351,CALLE,GENERAL LACY,NaN,28045
4994,CO20220219041504,COLON,Coche,42,Noche,2022-02-19,True,No festivo,04:10:00,S354,CALLE,BUSTAMANTE,0,28045

La fecha es la misma. El motivo de la retirada en ambas fue un rodaje de una película.  
La fecha fue la misma y el turno también fue el mismo, pero la grúa fue distinta.  
Dado que no necesito identificar vehículos en particular,  
cambiarle el nombre a 'idVehiculo' es mejor opción que eliminar una de las filas.

In [19]:
existe_valor = "CO20220219041505" in entradas2022['idVehiculo'].values

if existe_valor:
    print(f"El valor 'CO20220219041505' existe en la columna 'idVehiculo' del DataFrame 'entradas2022'.")
else:
    print(f"El valor 'CO20220219041505' no existe en la columna 'idVehiculo' del DataFrame 'entradas2022'.")

El valor 'CO20220219041505' no existe en la columna 'idVehiculo' del DataFrame 'entradas2022'.

El índice 'CO20220219041505' no está en uso. lo usaré como nuevo identificador, usando su índice implícito a uno de los dos.

In [20]:
entradas2022.loc[4994, 'idVehiculo'] = 'CO20220219041505'

Este Jupyter está siendo demasiado largo. He realizado la comprobación y efectivamente ya no está duplicado, se ha cambiado a uno de los dos.

Ahora uniré los DataFrames de los distintos años para tener un DataFrame, 'df_entradas', que recoja la información de los años 2016 al 2023.  
También comprobaré si de un año a otro se repiten los identificadores.

In [21]:
dataframes = [entradas2016, entradas2017, entradas2018, entradas2019, entradas2020, entradas2021, entradas2022, entradas2023]

In [22]:
df_entradas = pd.concat(dataframes, ignore_index=True)

In [23]:
filas_duplicadas_total = df_entradas[df_entradas.duplicated(subset=['idVehiculo'], keep=False)]
filas_duplicadas_total

Empty DataFrame
Columns: [idVehiculo, deposito, tipoVehiculo, motivo, turno, Fecha_e, FinDeSema, Festivo, Hora_e, grua, tipoVia, via, numero, cp]
Index: []

Los valores de 'idVehiculo' no se repiten de un año para otro. Por lo tanto, puedo utilizar la columna 'idVehiculo' en todos los años.

In [24]:
for indi in todos_los_años:
    print(f"#Codigo para el año {indi}")
    print(f"entradas{indi}.set_index('idVehiculo', inplace=True)")
    print()

#Codigo para el año 2016
entradas2016.set_index('idVehiculo', inplace=True)

#Codigo para el año 2017
entradas2017.set_index('idVehiculo', inplace=True)

#Codigo para el año 2018
entradas2018.set_index('idVehiculo', inplace=True)

#Codigo para el año 2019
entradas2019.set_index('idVehiculo', inplace=True)

#Codigo para el año 2020
entradas2020.set_index('idVehiculo', inplace=True)

#Codigo para el año 2021
entradas2021.set_index('idVehiculo', inplace=True)

#Codigo para el año 2022
entradas2022.set_index('idVehiculo', inplace=True)

#Codigo para el año 2023
entradas2023.set_index('idVehiculo', inplace=True)

In [25]:
#Codigo para el año 2016
entradas2016.set_index('idVehiculo', inplace=True)

#Codigo para el año 2017
entradas2017.set_index('idVehiculo', inplace=True)

#Codigo para el año 2018
entradas2018.set_index('idVehiculo', inplace=True)

#Codigo para el año 2019
entradas2019.set_index('idVehiculo', inplace=True)

#Codigo para el año 2020
entradas2020.set_index('idVehiculo', inplace=True)

#Codigo para el año 2021
entradas2021.set_index('idVehiculo', inplace=True)

#Codigo para el año 2022
entradas2022.set_index('idVehiculo', inplace=True)

#Codigo para el año 2023
entradas2023.set_index('idVehiculo', inplace=True)

In [26]:
entradas2019

,deposito,tipoVehiculo,motivo,turno,Fecha_e,FinDeSema,Festivo,Hora_e,grua,tipoVia,via,numero,cp
idVehiculo,,,,,,,,,,,,,
CO20190101010830,COLON,Coche,6,Noche,2019-01-01,False,Año Nuevo,01:07:00,S358,CALLE,GAVIOTA,35,28025
CO20190101021223,COLON,Coche,6,Noche,2019-01-01,False,Año Nuevo,02:11:00,S368,CALLE,TORRELAGUNA,110,28043
CO20190101021316,COLON,Coche,44,Noche,2019-01-01,False,Año Nuevo,02:12:00,S366,CALLE,PUEBLA DE MONTALBAN,18,28044
CO20190101021431,COLON,Coche,5,Noche,2019-01-01,False,Año Nuevo,02:13:00,S347,CALLE,BELZUNEGRI,0,28025
CO20190101021528,COLON,Coche,6,Noche,2019-01-01,False,Año Nuevo,02:14:00,S319,CALLE,GALVEZ,2,28044
...,...,...,...,...,...,...,...,...,...,...,...,...,...
CO20191230225259,COLON,Motocicleta,7,Noche,2019-12-30,False,No festivo,22:50:00,S354,CALLE,JORGE JUAN,0,28001
CO20191230225359,COLON,Motocicleta,7,Noche,2019-12-30,False,No festivo,22:50:00,S368,CALLE,JORGE JUAN,0,28001
VC20191230230711,VICALVARO,Coche,37,Noche,2019-12-30,False,No festivo,23:06:00,S363,GLORIETA,CADIZ,1,NaN
CO20191230233011,COLON,Motocicleta,7,Noche,2019-12-30,False,No festivo,23:28:00,S319,CALLE,SACRAMENTO,0,28005
M320191230235613,MEDIODIA 3,Camión,14,Noche,2019-12-30,False,No festivo,23:50:00,S320,CALLE,ALVAREZ ABELLAN,39,28025

Ahora guardaré los DataFrames, tanto de cada año como de todos los años unidos, en formato Parquet.  
He elegido este porque, preguntándolo a ChatGPT, me dice que mantiene mejor la estructura que CSV.

>Al intentar guardarlos en formato Parquet, los años 2019, 2020, 2021, 2022 y 2023 presentan problemas en 'tipoVehiculo'. Veré por qué.

In [27]:

año_tip = ['2019','2020','2021','2022','2023']
for tip in año_tip: 
    print(f"#codigo para el año{tip}")
    print(f"conteo_tipo_vehiculo = entradas{tip}['tipoVehiculo'].value_counts()")
    print("conteo_tipo_vehiculo")
    print()

#codigo para el año2019
conteo_tipo_vehiculo = entradas2019['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

#codigo para el año2020
conteo_tipo_vehiculo = entradas2020['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

#codigo para el año2021
conteo_tipo_vehiculo = entradas2021['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

#codigo para el año2022
conteo_tipo_vehiculo = entradas2022['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

#codigo para el año2023
conteo_tipo_vehiculo = entradas2023['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

In [28]:

#codigo para el año2019
conteo_tipo_vehiculo = entradas2019['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo
#codigo para el año2020
conteo_tipo_vehiculo = entradas2020['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo
#codigo para el año2021
conteo_tipo_vehiculo = entradas2021['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

#codigo para el año2022
conteo_tipo_vehiculo = entradas2022['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo
#codigo para el año2023
conteo_tipo_vehiculo = entradas2023['tipoVehiculo'].value_counts()
conteo_tipo_vehiculo

tipoVehiculo
Coche              29290
Motocicleta         4677
Camión              2792
Patinetes (VMP)      909
Bicicletas           112
Remolque              21
Vehículo pesado       13
Motocarro              9
Name: count, dtype: int64

Algunas entradas de la columna tipo de vehículo aparecen como 6.0, 7.0 y 8.0. Esto, como ya se ha dicho antes,  
no aparece en la tabla auxiliar. Mientras respondían al correo antes mencionado, puse "Desconocido6", "Desconocido7" y "Desconocido8".

Respondieron al correo con la siguiente información:
   
-**6.0: "Bicicletas"**  
-**7.0: "Patinetes (VMP)"**   
-**8.0: "Remolque"**  

>>La información la añadí en la misma línea de código que añadí la información que aparece en las tablas auxiliares.

Ahora si, guardo en formato parquet.

In [29]:
carpeta_salida = 'C:/Users/pepea/Desktop/the_drige/EDA/Dataset/entradas_validas'

for parque in todos_los_años: 
    print(f"#Codigo pra el el año {parque}:")
    print(f"nombre_archivo = 'entradas{parque}_util.parquet'")
    print(f"entradas{parque}.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)")
    print()

#Codigo pra el el año 2016:
nombre_archivo = 'entradas2016_util.parquet'
entradas2016.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2017:
nombre_archivo = 'entradas2017_util.parquet'
entradas2017.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2018:
nombre_archivo = 'entradas2018_util.parquet'
entradas2018.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2019:
nombre_archivo = 'entradas2019_util.parquet'
entradas2019.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2020:
nombre_archivo = 'entradas2020_util.parquet'
entradas2020.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2021:
nombre_archivo = 'entradas2021_util.parquet'
entradas2021.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2022:
nombre_archivo = 'entradas2022_util.parquet'
entradas2022.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2023:
nombre_archivo = 'entradas2023_util.parquet'
entradas2023.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

In [30]:
#Codigo pra el el año 2016:
nombre_archivo = 'entradas2016_util.parquet'
entradas2016.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2017:
nombre_archivo = 'entradas2017_util.parquet'
entradas2017.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2018:
nombre_archivo = 'entradas2018_util.parquet'
entradas2018.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2019:
nombre_archivo = 'entradas2019_util.parquet'
entradas2019.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2020:
nombre_archivo = 'entradas2020_util.parquet'
entradas2020.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2021:
nombre_archivo = 'entradas2021_util.parquet'
entradas2021.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2022:
nombre_archivo = 'entradas2022_util.parquet'
entradas2022.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

#Codigo pra el el año 2023:
nombre_archivo = 'entradas2023_util.parquet'
entradas2023.to_parquet(os.path.join(carpeta_salida, nombre_archivo), index=True)

In [31]:
entradas2020.head(3)

,deposito,tipoVehiculo,motivo,turno,Fecha_e,FinDeSema,Festivo,Hora_e,grua,tipoVia,via,numero,cp
idVehiculo,,,,,,,,,,,,,
CO20200101030251,COLON,Coche,6,Noche,2020-01-01,False,Año Nuevo,03:00:00,S357,CALLE,LEON V DE ARMENIA,9,28047
CO20200101031051,COLON,Coche,1,Noche,2020-01-01,False,Año Nuevo,03:10:00,S365,CALLE,CORREGIDOR MENDO DE ZUÑIGA,12,28030
CO20200101032037,COLON,Coche,44,Noche,2020-01-01,False,Año Nuevo,03:15:00,S349,AVENIDA,DOCTOR FEDERICO RUBIO Y GALI,19,28039

In [32]:
nombres_dataframes = ['entradas2016', 'entradas2017', 'entradas2018', 'entradas2019', 'entradas2020', 'entradas2021', 'entradas2022', 'entradas2023']
dataframes = [globals()[nombre] for nombre in nombres_dataframes]
df_entradas_util = pd.concat(dataframes)
df_entradas_util.head(3)

,deposito,tipoVehiculo,motivo,turno,Fecha_e,FinDeSema,Festivo,Hora_e,grua,tipoVia,via,numero,cp
idVehiculo,,,,,,,,,,,,,
CO20160101002327,Colón,Coche,1,Noche,2016-01-01,False,Año Nuevo,00:05:00,S032,CALLE,RIOCABADO,19,28047
CO20160101012710,Colón,Coche,9,Noche,2016-01-01,False,Año Nuevo,01:14:00,S219,CALLE,SANTA VIRGILIA,19,28033
CO20160101031613,Colón,Coche,44,Noche,2016-01-01,False,Año Nuevo,02:42:00,S223,TRAVESIA,LONGARES,10,28022

In [33]:
valores_unicos_tipo_arreglado = df_entradas_util['tipoVehiculo'].unique()
valores_unicos_tipo_arreglado

array(['Coche', 'Motocicleta', 'Camión', 'Vehículo pesado', 'Motocarro',
       'Bicicletas', 'Patinetes (VMP)', 'Remolque'], dtype=object)

In [34]:
df_entradas_util.to_parquet(os.path.join('C:/Users/pepea/Desktop/the_drige/EDA/Dataset/entradas_validas', 'df_entradas_util.parquet'), index=True)

<img src="./IA/cansada.jpg" width=600><sub><sup>

<small>Imagen creada por IA generativa usando el siguiente pront "dibujame una grua de remolcar coches, algo antropomorfa, que se le vea cansada. Tipo dibujo animado.<small>